'use strict';

(function () {

  var STATUS_OK = 200;
  var TIMEOUT = 10000;

  var MAX_AVATARS = 6;
  var PICTURE_HEIGHT = 35;
  var ESC_CODE = 27;
  var ENTER_CODE = 13;
  var MAX_COMMENTS = 5;

  var MAX_COMMENTS_IN_PICS = 10;
  var MIN_LIKES = 15;
  var MAX_LIKES = 185;

  var MIN_SCALE_VALUE = 25;
  var MAX_SCALE_VALUE = 100;
  var JUMP_VALUE = 25;
  var DEFAULT_SCALE = 100;
  var DEFAULT_RIGHT = 453;
  var MAX_COUNT_HASHTAGS = 5;
  var LEFT_EDGE = 0;
  var MAX_DESCRIPTION_LENGTH = 140;
  var DEBOUNCE_INTERVAL = 500;
  window.constant = {
    STATUS_OK: STATUS_OK,
    TIMEOUT: TIMEOUT,
    MAX_AVATARS: MAX_AVATARS,
    PICTURE_HEIGHT: PICTURE_HEIGHT,
    ESC_CODE: ESC_CODE,
    MAX_COMMENTS: MAX_COMMENTS,
    MAX_COMMENTS_IN_PICS: MAX_COMMENTS_IN_PICS,
    MIN_LIKES: MIN_LIKES,
    MAX_LIKES: MAX_LIKES,
    MIN_SCALE_VALUE: MIN_SCALE_VALUE,
    MAX_SCALE_VALUE: MAX_SCALE_VALUE,
    JUMP_VALUE: JUMP_VALUE,
    DEFAULT_SCALE: DEFAULT_SCALE,
    DEFAULT_RIGHT: DEFAULT_RIGHT,
    MAX_COUNT_HASHTAGS: MAX_COUNT_HASHTAGS,
    LEFT_EDGE: LEFT_EDGE,
    ENTER_CODE: ENTER_CODE,
    MAX_DESCRIPTION_LENGTH: MAX_DESCRIPTION_LENGTH,
    DEBOUNCE_INTERVAL: DEBOUNCE_INTERVAL
  };
})();
